### ISSUE TITLE
你

### ISSUE THREAD

**Issue by Eliauk-Vae** [beibeiaiwuhao/bbmanage#1]

**Comment by beibeiaiwuhao** [comment]
这个是我自己写的项目，没有教学视频的

**Comment by 15997357611** [comment]
那请问下有开发文档么



15997357611@163.com
 
发件人： beibeiaiwuhao
发送时间： 2019-11-08 10:16
收件人： beibeiaiwuhao/bbmanage
抄送： 15997357611; Author
主题： Re: [beibeiaiwuhao/bbmanage] 你好 请问下有这个项目的教学视频链接么 (#1)
这个是我自己写的项目，没有教学视频的

**Comment by beibeiaiwuhao** [comment]
不好意思，这个也没有，项目比较简单，你可以直接运行看
